#!/bin/bash
# Surfaces backup failure. Runs on its own schedule, not from the backup jobs,
# so a job that dies or never starts is still caught.
#
# Alerts when the local backup is missing or stale, when it is implausibly
# small, or when the off site copy is missing or stale. Alerting reuses the
# mail path the host already has; if that is absent it writes to the system log
# and to a state file, so the failure is visible either way.
#
# Exit status is 0 when everything is healthy and 1 when an alert fired, so it
# can also be called from a shell and read by a human.
set -uo pipefail

# Exit 10 means the check found a problem and has already notified. cron-run.sh
# treats it as reported and stays quiet, so one event produces one mail. Any
# other non-zero means the check itself broke, which cron-run.sh does mail,
# because at that point nothing else will.
EXIT_ALERT_SENT=10


BACKUP_DIR=/opt/astraeusio/backups
STATE=/var/lib/astraeusio-backup-state
# The backup runs at 03:00 and this check at 04:00 and 16:00, so the oldest a
# healthy backup is ever seen is 13 hours, at the afternoon check. A missed
# nightly run shows as 25 hours at the next 04:00 check. 20 hours sits between
# the two with seven hours of margin either side, so a failed nightly is caught
# the same morning instead of a day later. The old value of 30 could not tell
# the two apart at all.
LOCAL_MAX_AGE_H=20
OFFSITE_MAX_AGE_H=20
MIN_SIZE_BYTES=$((500 * 1024 * 1024))
# Delivery moved to notify.sh, which owns the recipient, the sender and
# the API key. Leaving these here would read as if they still controlled
# where alerts go, and they do not.

# Exercisable without alerting. NOTIFY_SEND=0 silences every script on this
# host at once, since all of them send through notify.sh; this is the local
# switch, for exercising this check alone. Both exist because neither was set
# when a harness ran poller-check.sh against fixture logs and mailed 37 alerts
# in eleven seconds. The harness isolated state and data correctly and did not
# isolate the effect the script exists to produce.
SEND_MAIL=${BACKUP_CHECK_MAIL:-1}

send_mail() {
  local subject=$1 body=$2
  if [ "$SEND_MAIL" != "1" ]; then
    echo "  (mail suppressed by BACKUP_CHECK_MAIL=$SEND_MAIL: $subject)"
    return 0
  fi
  /opt/astraeusio/notify.sh "$subject" "$body" 2>&1 | sed 's/^/  /'
}

problems=()

# Local backup present, fresh, and a plausible size.
# shellcheck disable=SC2012  # names are generated by backup.sh as
# astraeus_YYYYMMDD.duckdb, so there is no whitespace or newline to mishandle,
# and ls -t is the clearest way to take the newest by mtime.
latest=$(ls -t "$BACKUP_DIR"/astraeus_*.duckdb 2>/dev/null | head -n 1 || true)
if [ -z "$latest" ]; then
  problems+=("no local backup found in $BACKUP_DIR")
else
  age_h=$(( ( $(date +%s) - $(stat -c %Y "$latest") ) / 3600 ))
  size=$(stat -c %s "$latest")
  if [ "$age_h" -gt "$LOCAL_MAX_AGE_H" ]; then
    problems+=("local backup $(basename "$latest") is ${age_h}h old, limit ${LOCAL_MAX_AGE_H}h")
  fi
  if [ "$size" -lt "$MIN_SIZE_BYTES" ]; then
    problems+=("local backup $(basename "$latest") is only $size bytes")
  fi
fi

# Off site copy present and fresh. Read only listing, object read permission.
offsite=$(python3 /opt/astraeusio/r2_latest.py 2>/dev/null || true)
if [ -z "$offsite" ]; then
  problems+=("could not list the off site bucket")
else
  off_key=$(echo "$offsite" | cut -d' ' -f1)
  off_age_h=$(echo "$offsite" | cut -d' ' -f2)
  if [ "$off_age_h" = "none" ]; then
    problems+=("no off site backup object found")
  elif [ "$off_age_h" -gt "$OFFSITE_MAX_AGE_H" ]; then
    problems+=("off site $off_key is ${off_age_h}h old, limit ${OFFSITE_MAX_AGE_H}h")
  fi
fi

mkdir -p "$(dirname "$STATE")"

if [ "${#problems[@]}" -eq 0 ]; then
  echo "$(date -u): backup check ok"
  echo "ok $(date -u +%s)" > "$STATE"
  exit 0
fi

body="Astraeusio backup check failed at $(date -u)

$(printf '  %s\n' "${problems[@]}")

Local backups: $BACKUP_DIR
Host: $(hostname)"

echo "$(date -u): backup check FAILED"
printf '  %s\n' "${problems[@]}"
echo "fail $(date -u +%s)" > "$STATE"

# Always log to the journal, which is retained and greppable.
echo "$body" | logger -t astraeusio-backup -p daemon.err

# Mail if the host has a working mailer. Not fatal if it does not.
send_mail "Astraeusio backup check FAILED" "$body" || true

exit "$EXIT_ALERT_SENT"
