#!/bin/bash
# Uploads the newest local backup to R2.
#
# The previous version sent the whole file in one PUT to the Cloudflare REST
# API, which caps a single request at 300 MiB. It worked until the compressed
# backup passed that size and then failed every night for six weeks with
# HTTP 413. This uses the S3 API with multipart instead, through a token
# scoped to this bucket with object read and write only.
#
# Verification never compares the ETag. A multipart ETag is the md5 of the
# concatenated part md5s with a dash and the part count, so it never equals the
# md5 of the file. The upload stores the local sha256 as object metadata and
# reads it back.
set -euo pipefail

BACKUP_DIR=/opt/astraeusio/backups
UPLOADER=/opt/astraeusio/r2_upload.py

log() { echo "$(date -u): $*"; }

# shellcheck disable=SC2012  # names are generated by backup.sh as

# astraeus_YYYYMMDD.duckdb, so there is no whitespace or newline to mishandle,

# and ls -t is the clearest way to take the newest by mtime.

LATEST=$(ls -t "$BACKUP_DIR"/astraeus_*.duckdb 2>/dev/null | head -n 1 || true)
if [ -z "$LATEST" ]; then
  echo "$(date -u): no backups found in $BACKUP_DIR" >&2
  exit 1
fi

TMP=$(mktemp /tmp/astraeus_backup.XXXXXX.gz)
trap 'rm -f "$TMP"' EXIT

gzip -c "$LATEST" > "$TMP"
NAME=$(basename "$LATEST" .duckdb).gz
log "uploading $NAME ($(du -h "$TMP" | cut -f1) compressed)"

if ! python3 "$UPLOADER" "$TMP" "$NAME"; then
  echo "$(date -u): off site upload FAILED for $NAME" >&2
  exit 1
fi

log "off site backup uploaded and verified: $NAME"

# Off site retention is deliberately not pruning. The previous filter matched
# keys ending in .duckdb.gz while objects are named astraeus_YYYYMMDD.gz, so it
# never deleted anything and the bucket still holds every object since May.
# Repairing it would delete 27 objects on the next run, including
# astraeus_20260627.gz, the last copy known to predate the six week outage.
# Retention needs an explicit decision about what to keep before it is enabled.
